<?php
// --- Category Map ---
// Single source of truth: filename => category. Unmapped sheets fall back to "Other".
// Add one line here when you publish a new cheatsheet.
return [
    // AI & Safety
    'agi-development-guide.html' => 'AI & Safety',
    'ai-coding-agents-compared.html' => 'AI & Safety',
    'ai-frontier.html' => 'AI & Safety',
    'ai-model-api-pricing.html' => 'AI & Safety',
    'ai-model-picker.html' => 'AI & Safety',
    'ai-models-compared.html' => 'AI & Safety',
    'ai-progress-dashboard.html' => 'AI & Safety',
    'ai-safety-existential-risk.html' => 'AI & Safety',
    'ai-risk-timeline.html' => 'AI & Safety',
    'airisk.html' => 'AI & Safety',
    'aisafety.html' => 'AI & Safety',
    'google-ai-studio-guide.html' => 'AI & Safety',
    'governing-agentic-ai.html' => 'AI & Safety',
    'how-its-built.html' => 'AI & Safety',
    'p-doom-calculator.html' => 'AI & Safety',
    'p-doom-test-harness.html' => 'AI & Safety',
    'prompt-builder.html' => 'AI & Safety',
    'open-weight-ai-models.html' => 'AI & Safety',
    'yudkowsky-rationality-ai-cheatsheet.html' => 'AI & Safety',

    // Software & DevOps
    'aws-vs-azure.html' => 'Software & DevOps',
    'azure-devops.html' => 'Software & DevOps',
    'api-design-rest-graphql-grpc-webhooks.html' => 'Software & DevOps',
    'clean-architecture-dotnet.html' => 'Software & DevOps',
    'compression-algorithms.html' => 'Software & DevOps',
    'databases.html' => 'Software & DevOps',
    'dotnet-cheatsheet.html' => 'Software & DevOps',
    'git-internals.html' => 'Software & DevOps',
    'git-scm.html' => 'Software & DevOps',
    'javascript-for-architects.html' => 'Software & DevOps',
    'microservices.html' => 'Software & DevOps',
    'modern-devops-pipelines.html' => 'Software & DevOps',
    'observability-logs-metrics-traces-slos.html' => 'Software & DevOps',
    'postgresql.html' => 'Software & DevOps',
    'python-for-architects.html' => 'Software & DevOps',
    'scrum.html' => 'Software & DevOps',
    'software-development-guides.html' => 'Software & DevOps',
    'sql-performance-tuning.html' => 'Software & DevOps',
    'ubuntu-linux-for-ai-developers.html' => 'Software & DevOps',
    'versioncontrol.html' => 'Software & DevOps',

    // Security & Privacy
    'linux-server-hardening.html' => 'Security & Privacy',
    'passkeys-yubikeys-hardware-auth.html' => 'Security & Privacy',
    'personal-cybersecurity.html' => 'Security & Privacy',
    'post-quantum-cryptography.html' => 'Security & Privacy',
    'privacy-data-broker-opt-out.html' => 'Security & Privacy',

    // Risk & Preparedness
    'actual-risk-dashboard.html' => 'Risk & Preparedness',
    'celestial-navigation.html' => 'Risk & Preparedness',
    'creator-public-figure-threat-model.html' => 'Risk & Preparedness',
    'how-burglars-break-in.html' => 'Risk & Preparedness',
    'nuclear-preparedness.html' => 'Risk & Preparedness',
    'parents-threat-model.html' => 'Risk & Preparedness',
    'prepper-gear-audit.html' => 'Risk & Preparedness',
    'safes-what-they-stop.html' => 'Risk & Preparedness',
    'security-theater-audit.html' => 'Risk & Preparedness',
    'vehicle-emergency-kit.html' => 'Risk & Preparedness',

    // Bitcoin & Finance
    'bitcoin-exchanges-cards.html' => 'Bitcoin & Finance',
    'bitcoin-self-custody-guide.html' => 'Bitcoin & Finance',
    'bitcoin-wallet.html' => 'Bitcoin & Finance',
    'bitcoin-whitepaper.html' => 'Bitcoin & Finance',
    'currency-timeline.html' => 'Bitcoin & Finance',
    'housing-comparison.html' => 'Bitcoin & Finance',
    'index-investing-tax-advantaged.html' => 'Bitcoin & Finance',
    'lifestyle-calculator.html' => 'Bitcoin & Finance',
    'the-cliff-map.html' => 'Bitcoin & Finance',

    // Martial Arts & Strategy
    'art-of-war-sun-tzu.html' => 'Martial Arts & Strategy',
    'ashihara-karate.html' => 'Martial Arts & Strategy',
    'brazilian-jiu-jitsu.html' => 'Martial Arts & Strategy',
    'judo.html' => 'Martial Arts & Strategy',
    'martial-arts-cheatsheet.html' => 'Martial Arts & Strategy',

    // Firearms & Military
    'autonomous-defense-systems.html' => 'Firearms & Military',
    'future-of-warfare-technology.html' => 'Firearms & Military',
    'handgun-calibers.html' => 'Firearms & Military',
    'military-aphorisms.html' => 'Firearms & Military',
    'modern-firearms.html' => 'Firearms & Military',
    'operator-loadouts.html' => 'Firearms & Military',

    // Radio
    'baofeng-uv5r-ham-guide.html' => 'Radio',
    'baofeng-uv5r-quick-ref.html' => 'Radio',
    'emergency-radio-card.html' => 'Radio',
    'ham-radio-technician.html' => 'Radio',

    // Health & Fitness
    'blood-tests-cbc-cmp-lipids-a1c-thyroid.html' => 'Health & Fitness',
    'cycling.html' => 'Health & Fitness',
    'longevity-biomarkers.html' => 'Health & Fitness',
    'longevity-supplements-evidence.html' => 'Health & Fitness',
    'longevity-what-actually-works.html' => 'Health & Fitness',
    'er-triage.html' => 'Health & Fitness',
    'hospital-stay-survival.html' => 'Health & Fitness',
    'human-skeleton.html' => 'Health & Fitness',
    'medical-school-curriculum.html' => 'Health & Fitness',
    'nnt-medical-interventions.html' => 'Health & Fitness',
    'reassurance-tables.html' => 'Health & Fitness',
    'running.html' => 'Health & Fitness',
    'sleep-optimization.html' => 'Health & Fitness',
    'strength-training.html' => 'Health & Fitness',
    'veterinary-diagnostics.html' => 'Health & Fitness',
    'weight-loss-levers.html' => 'Health & Fitness',
    'weightloss-cheatsheet.html' => 'Health & Fitness',

    // Philosophy & Religion
    'anatta-not-self.html' => 'Philosophy & Religion',
    'anapanasati-mindfulness-of-breathing.html' => 'Philosophy & Religion',
    'anger-buddhist-cognitive-debugging.html' => 'Philosophy & Religion',
    'buddhism-core-principles.html' => 'Philosophy & Religion',
    'buddhism.html' => 'Philosophy & Religion',
    'buddhist-work-leadership.html' => 'Philosophy & Religion',
    'capitalism.html' => 'Philosophy & Religion',
    'comparative-religion-map.html' => 'Philosophy & Religion',
    'conscious-leadership-contexts.html' => 'Philosophy & Religion',
    'craving-desire-habit-loops.html' => 'Philosophy & Religion',
    'decision-theory-everyday-life.html' => 'Philosophy & Religion',
    'etz-chaim-tree-of-life.html' => 'Philosophy & Religion',
    'five-hindrances-debugger.html' => 'Philosophy & Religion',
    'islam.html' => 'Philosophy & Religion',
    'israel-history.html' => 'Philosophy & Religion',
    'judaism.html' => 'Philosophy & Religion',
    'leadership.html' => 'Philosophy & Religion',
    'objectivism.html' => 'Philosophy & Religion',
    'right-speech-modern-life.html' => 'Philosophy & Religion',
    'satipatthana-four-foundations.html' => 'Philosophy & Religion',
    'shabbat-services-cheatsheet.html' => 'Philosophy & Religion',
    'stoicism-practice-texts-misreadings.html' => 'Philosophy & Religion',

    // Engineering & Science
    'ai-accelerator-comparison.html' => 'Engineering & Science',
    'ai-infrastructure-numbers.html' => 'Engineering & Science',
    'automotive-innovation-timeline.html' => 'Engineering & Science',
    'boom-supersonic.html' => 'Engineering & Science',
    'data-center-community-impact.html' => 'Engineering & Science',
    'data-center-myths.html' => 'Engineering & Science',
    'datacenter-cooling-thresholds.html' => 'Engineering & Science',
    'datacenter-power-chain.html' => 'Engineering & Science',
    'deaths-per-terawatt-hour.html' => 'Engineering & Science',
    'engineering-materials-future.html' => 'Engineering & Science',
    'engineering-metals-selection.html' => 'Engineering & Science',
    'geoengineering-approaches.html' => 'Engineering & Science',
    'human-evolution.html' => 'Engineering & Science',
    'humanoid-robots.html' => 'Engineering & Science',
    'nuclear-power-reactor-types.html' => 'Engineering & Science',
    'orbital-rockets-comparison.html' => 'Engineering & Science',
    'rockets-and-spaceflight.html' => 'Engineering & Science',
    'semiconductor-manufacturing.html' => 'Engineering & Science',
    'sensors-cameras-lidar-radar-imu-gps.html' => 'Engineering & Science',
    'space-habitats-life-support.html' => 'Engineering & Science',
    'starlink-satellite-anatomy.html' => 'Engineering & Science',
    'stellar-lifecycle.html' => 'Engineering & Science',
    'tesla-products.html' => 'Engineering & Science',

    // Home & Lifestyle
    'amish-technology-decisions.html' => 'Home & Lifestyle',
    'baby-gear-audit.html' => 'Home & Lifestyle',
    'command-deck.html' => 'Home & Lifestyle',
    'cooking-guide.html' => 'Home & Lifestyle',
    'air-water-filtration.html' => 'Home & Lifestyle',
    'global_cuisine_guide.html' => 'Home & Lifestyle',
    'home-electrical-basics.html' => 'Home & Lifestyle',
    'home-maintenance-guide.html' => 'Home & Lifestyle',
    'hot-tub-treatment.html' => 'Home & Lifestyle',
    'lawn-irrigation-watering-math.html' => 'Home & Lifestyle',
    'living-richly-guide.html' => 'Home & Lifestyle',
    'samsung-bespoke-oven-guide.html' => 'Home & Lifestyle',
    'the-glue-chart.html' => 'Home & Lifestyle',
    'the-household-numbers.html' => 'Home & Lifestyle',

    // Life Admin & Consumer Defense
    'audit-odds.html' => 'Life Admin & Consumer Defense',
    'auto-repair-decoder.html' => 'Life Admin & Consumer Defense',
    'contract-red-flags.html' => 'Life Admin & Consumer Defense',
    'death-logistics.html' => 'Life Admin & Consumer Defense',
    'debt-collection-defense.html' => 'Life Admin & Consumer Defense',
    'estate-documents.html' => 'Life Admin & Consumer Defense',
    'eyeglasses-decoded.html' => 'Life Admin & Consumer Defense',
    'first-employee-checklist.html' => 'Life Admin & Consumer Defense',
    'flight-disruption-playbook.html' => 'Life Admin & Consumer Defense',
    'hiring-a-contractor.html' => 'Life Admin & Consumer Defense',
    'insurance-worth-it.html' => 'Life Admin & Consumer Defense',
    'scam-defense-for-parents.html' => 'Life Admin & Consumer Defense',
    'small-business-scams.html' => 'Life Admin & Consumer Defense',
    'small-claims-court.html' => 'Life Admin & Consumer Defense',
    'the-free-version-exists.html' => 'Life Admin & Consumer Defense',
];
