/* One state object drives the local controls of the shared optical apparatus. */
(()=>{'use strict';
const R=window.Rainbow,data=JSON.parse(document.getElementById('rainbow-data').textContent);
const state={observer:0,elevation:15,b:R.stationary(data.ray_presets[0].n).b,wavelength:0,neighbors:true,radius:100,airy:true,mie:true};
const el=id=>document.getElementById(id),put=(id,html)=>{el(id).innerHTML=html;};
let announcement;
function say(text){clearTimeout(announcement);announcement=setTimeout(()=>el('live-status').textContent=text,250);}
function observer(){const s=R.observerState(state.observer,state.elevation);put('cone-figure',R.cone(state.observer,state.elevation));put('full-cone',R.cone(state.observer,state.elevation));put('sky-figure',R.sky(state.observer,state.elevation));put('side-figure',R.side(state.observer,state.elevation));put('inset-figure',R.observerDrop(state.observer,state.elevation));el('observer-a').setAttribute('aria-pressed',String(!state.observer));el('observer-b').setAttribute('aria-pressed',String(!!state.observer));const text=`Observer ${state.observer?'B':'A'} · Sun ${state.elevation}° · top ${(s.beta-state.elevation).toFixed(1)}° above horizon · ${s.drops.filter(d=>d.selected).length} selected sample drops.`;el('observer-summary').textContent=text;say(text);heroSun();}
function ray(){const preset=data.ray_presets[state.wavelength],t=R.trace(state.b,preset.n),g=R.stationary(preset.n);put('ray-figure',R.drop(state.b,preset.n,1,state.neighbors));el('ray-figure').style.setProperty('--ray-color',['var(--accent)','light-dark(#247455,#80cfa8)','var(--blue)'][state.wavelength]);put('deflection-figure',R.deflection(state.b,preset.n));const text=`${preset.nm} nm · n = ${preset.n.toFixed(5)} · b/a = ${state.b.toFixed(3)} · selected β = ${t.beta.toFixed(2)}° · stationary β = ${g.beta.toFixed(2)}°. Water 20°C, 998.2 kg/m³; exterior index 1.`;el('ray-summary').textContent=text;say(text);}
function wave(){const c=data.cases[String(state.radius)];for(const [id,polar,compact] of [['wave-figure',false,false],['wave-mobile',false,true],['polarization-figure',true,false],['polarization-mobile',true,true]])put(id,R.wave(data,state.radius,state.airy,state.mie,polar,compact));const text=`a = ${state.radius} μm · λ = 650 nm · n = 1.332 · x = ${c.x.toFixed(3)} · Airy scale ${c.scale_degrees.toFixed(4)}° · isolated lossless sphere, plane wave.`;el('wave-summary').textContent=text;el('polarization-caption').textContent=`${state.radius} μm radius, 650 nm, n = 1.332. Both curves share the perpendicular peak as denominator, preserving relative strength. This panel always shows both polarizations; the model checkboxes affect the comparison above.`;say(text);}
el('observer-a').addEventListener('click',()=>{state.observer=0;observer();});el('observer-b').addEventListener('click',()=>{state.observer=1;observer();});el('sun').addEventListener('input',e=>{state.elevation=+e.target.value;observer();});el('reset-observer').addEventListener('click',()=>{state.observer=0;state.elevation=15;el('sun').value=15;observer();});
el('impact').addEventListener('input',e=>{state.b=+e.target.value;ray();});el('wavelength').addEventListener('change',e=>{state.wavelength=+e.target.value;ray();});el('neighbors').addEventListener('change',e=>{state.neighbors=e.target.checked;ray();});el('reset-ray').addEventListener('click',()=>{state.b=R.stationary(data.ray_presets[state.wavelength].n).b;el('impact').value=state.b;ray();});
el('radius').addEventListener('change',e=>{state.radius=+e.target.value;wave();});for(const id of ['airy','mie'])el('show-'+id).addEventListener('change',e=>{state[id]=e.target.checked;wave();});
// The opening bow is the same computed gradient as every other figure: the Sun slider moves its
// antisolar centre, and the pointer reads angle, wavelength and index straight off the sky.
const hero=document.querySelector('.hero'),heroModel=R.heroBow(state.elevation),hg=heroModel.geometry,[pv,pr]=heroModel.primary,[sr,sv]=heroModel.secondary;
function heroSun(){if(!el('hero-sun'))return;const cy=hg.horizon+state.elevation*hg.k;for(const id of ['hero-bow-grad','hero-band-grad','hero-ring'])el(id).setAttribute('cy',cy);el('hero-radius').setAttribute('y1',cy);el('hero-sun').value=state.elevation;const top=pr-state.elevation;el('hero-sun-out').textContent=`${state.elevation}° up · `+(top>0?`bow top ${top.toFixed(0)}° above the horizon`:sv-state.elevation>0?'primary below the horizon, secondary remains':'both bows below a level horizon');}
el('hero-sun').addEventListener('input',e=>{state.elevation=+e.target.value;el('sun').value=state.elevation;observer();});
function wavelengthAt(beta,p){const f=nm=>R.stationary(R.indexAt(nm),p).beta,inc=f(700)>f(400);let lo=400,hi=700;for(let j=0;j<28;j++){const mid=(lo+hi)/2;if((f(mid)<beta)===inc)lo=mid;else hi=mid;}return (lo+hi)/2;}
const geom=el('hero-geom'),probe=el('hero-probe');
function probeAt(e){if(e.target.closest('.hero-sun')||e.target.closest('.masthead a')){hideProbe();return;}const pt=new DOMPoint(e.clientX,e.clientY).matrixTransform(geom.getScreenCTM().inverse()),cy=hg.horizon+state.elevation*hg.k,dx=pt.x-hg.cx,dy=pt.y-cy,beta=Math.hypot(dx,dy)/hg.k;
 let head,body;if(beta<pv-.25){head='Inside the bow';body=`β = ${beta.toFixed(1)}° from the antisolar point. Every wavelength’s one-reflection light overlaps here, so the sky is brighter.`;}
 else if(beta<pr+.15){const nm=wavelengthAt(Math.min(pr,Math.max(pv,beta)),2);head='Primary bow';body=`β = ${beta.toFixed(1)}° · ${nm.toFixed(0)} nm · n = ${R.indexAt(nm).toFixed(4)}. One internal reflection.`;}
 else if(beta<sr-.15){head='Alexander’s band';body=`β = ${beta.toFixed(1)}°. No one- or two-reflection ray leaves a drop between ${pr.toFixed(1)}° and ${sr.toFixed(1)}°.`;}
 else if(beta<sv+.2){const nm=wavelengthAt(Math.min(sv,Math.max(sr,beta)),3);head='Secondary bow';body=`β = ${beta.toFixed(1)}° · ${nm.toFixed(0)} nm · n = ${R.indexAt(nm).toFixed(4)}. Two reflections, order reversed.`;}
 else{head='Outside the secondary';body=`β = ${beta.toFixed(1)}°. Only weaker higher-order paths and diffuse sky light.`;}
 if(pt.y>hg.horizon)body+=' Below a level horizon this direction meets ground, not rain.';
 el('hero-ring').setAttribute('r',beta*hg.k);el('hero-radius').setAttribute('x2',pt.x);el('hero-radius').setAttribute('y2',pt.y);geom.classList.add('active');
 const box=hero.getBoundingClientRect();probe.innerHTML=`<b>${head}</b>${body}`;probe.hidden=false;const flip=e.clientX-box.left>box.width-270;probe.style.left=(e.clientX-box.left-(flip?270:0))+'px';probe.style.top=(e.clientY-box.top-(e.clientY-box.top>box.height-90?90:0))+'px';}
function hideProbe(){probe.hidden=true;geom.classList.remove('active');}
if(geom&&probe){hero.addEventListener('pointermove',probeAt);hero.addEventListener('pointerdown',probeAt);hero.addEventListener('pointerleave',hideProbe);}
// The depth nav marks the chapter under the reader and keeps that link scrolled into view on narrow screens.
const navLinks=[...document.querySelectorAll('.depth-nav a')],navWrap=document.querySelector('.depth-nav .wrap');
if('IntersectionObserver' in window&&navLinks.length){const byId=new Map(navLinks.map(a=>[a.getAttribute('href').slice(1),a]));
 const io=new IntersectionObserver(entries=>{for(const e of entries){if(!e.isIntersecting)continue;const a=byId.get(e.target.id);if(!a)continue;navLinks.forEach(l=>l.removeAttribute('aria-current'));a.setAttribute('aria-current','true');if(navWrap.scrollWidth>navWrap.clientWidth)navWrap.scrollTo({left:Math.max(0,a.offsetLeft-navWrap.clientWidth/2+a.offsetWidth/2),behavior:matchMedia('(prefers-reduced-motion:no-preference)').matches?'smooth':'instant'});}},{rootMargin:'-40% 0px -55% 0px'});
 byId.forEach((a,id)=>{const s=document.getElementById(id);if(s)io.observe(s);});}
// Native disclosures become ordinary expanded scientific text in print.
let previouslyClosed=[];addEventListener('beforeprint',()=>{previouslyClosed=[...document.querySelectorAll('details:not([open])')];previouslyClosed.forEach(d=>d.open=true);});addEventListener('afterprint',()=>previouslyClosed.forEach(d=>d.open=false));
el('impact').value=state.b;ray();clearTimeout(announcement);document.documentElement.classList.add('enhanced');
})();
