/* One state object drives the local controls of the shared optical apparatus. */
(()=>{'use strict';
const R=window.Rainbow,data=JSON.parse(document.getElementById('rainbow-data').textContent);
const state={observer:0,elevation:15,b:R.stationary(data.ray_presets[0].n).b,wavelength:0,neighbors:true,radius:100,airy:true,mie:true};
const el=id=>document.getElementById(id),put=(id,html)=>{el(id).innerHTML=html;};
let announcement;
function say(text){clearTimeout(announcement);announcement=setTimeout(()=>el('live-status').textContent=text,250);}
function observer(){const s=R.observerState(state.observer,state.elevation);put('cone-figure',R.cone(state.observer,state.elevation));put('full-cone',R.cone(state.observer,state.elevation));put('sky-figure',R.sky(state.observer,state.elevation));put('side-figure',R.side(state.observer,state.elevation));put('inset-figure',R.observerDrop(state.observer,state.elevation));el('observer-a').setAttribute('aria-pressed',String(!state.observer));el('observer-b').setAttribute('aria-pressed',String(!!state.observer));const text=`Observer ${state.observer?'B':'A'} · Sun ${state.elevation}° · top ${(s.beta-state.elevation).toFixed(1)}° above horizon · ${s.drops.filter(d=>d.selected).length} selected sample drops.`;el('observer-summary').textContent=text;say(text);}
function ray(){const preset=data.ray_presets[state.wavelength],t=R.trace(state.b,preset.n),g=R.stationary(preset.n);put('ray-figure',R.drop(state.b,preset.n,1,state.neighbors));el('ray-figure').style.setProperty('--ray-color',['var(--accent)','light-dark(#247455,#80cfa8)','var(--blue)'][state.wavelength]);put('deflection-figure',R.deflection(state.b,preset.n));const text=`${preset.nm} nm · n = ${preset.n.toFixed(5)} · b/a = ${state.b.toFixed(3)} · selected β = ${t.beta.toFixed(2)}° · stationary β = ${g.beta.toFixed(2)}°. Water 20°C, 998.2 kg/m³; exterior index 1.`;el('ray-summary').textContent=text;say(text);}
function wave(){const c=data.cases[String(state.radius)];for(const [id,polar,compact] of [['wave-figure',false,false],['wave-mobile',false,true],['polarization-figure',true,false],['polarization-mobile',true,true]])put(id,R.wave(data,state.radius,state.airy,state.mie,polar,compact));const text=`a = ${state.radius} μm · λ = 650 nm · n = 1.332 · x = ${c.x.toFixed(3)} · Airy scale ${c.scale_degrees.toFixed(4)}° · isolated lossless sphere, plane wave.`;el('wave-summary').textContent=text;el('polarization-caption').textContent=`${state.radius} μm radius, 650 nm, n = 1.332. Both curves share the perpendicular peak as denominator, preserving relative strength. This panel always shows both polarizations; the model checkboxes affect the comparison above.`;say(text);}
el('observer-a').addEventListener('click',()=>{state.observer=0;observer();});el('observer-b').addEventListener('click',()=>{state.observer=1;observer();});el('sun').addEventListener('input',e=>{state.elevation=+e.target.value;observer();});el('reset-observer').addEventListener('click',()=>{state.observer=0;state.elevation=15;el('sun').value=15;observer();});
el('impact').addEventListener('input',e=>{state.b=+e.target.value;ray();});el('wavelength').addEventListener('change',e=>{state.wavelength=+e.target.value;ray();});el('neighbors').addEventListener('change',e=>{state.neighbors=e.target.checked;ray();});el('reset-ray').addEventListener('click',()=>{state.b=R.stationary(data.ray_presets[state.wavelength].n).b;el('impact').value=state.b;ray();});
el('radius').addEventListener('change',e=>{state.radius=+e.target.value;wave();});for(const id of ['airy','mie'])el('show-'+id).addEventListener('change',e=>{state[id]=e.target.checked;wave();});
// The depth nav marks the chapter under the reader and keeps that link scrolled into view on narrow screens.
const navLinks=[...document.querySelectorAll('.depth-nav a')],navWrap=document.querySelector('.depth-nav .wrap');
if('IntersectionObserver' in window&&navLinks.length){const byId=new Map(navLinks.map(a=>[a.getAttribute('href').slice(1),a]));
 const io=new IntersectionObserver(entries=>{for(const e of entries){if(!e.isIntersecting)continue;const a=byId.get(e.target.id);if(!a)continue;navLinks.forEach(l=>l.removeAttribute('aria-current'));a.setAttribute('aria-current','true');if(navWrap.scrollWidth>navWrap.clientWidth)navWrap.scrollTo({left:Math.max(0,a.offsetLeft-navWrap.clientWidth/2+a.offsetWidth/2),behavior:matchMedia('(prefers-reduced-motion:no-preference)').matches?'smooth':'instant'});}},{rootMargin:'-40% 0px -55% 0px'});
 byId.forEach((a,id)=>{const s=document.getElementById(id);if(s)io.observe(s);});}
// Native disclosures become ordinary expanded scientific text in print.
let previouslyClosed=[];addEventListener('beforeprint',()=>{previouslyClosed=[...document.querySelectorAll('details:not([open])')];previouslyClosed.forEach(d=>d.open=true);});addEventListener('afterprint',()=>previouslyClosed.forEach(d=>d.open=false));
el('impact').value=state.b;ray();clearTimeout(announcement);document.documentElement.classList.add('enhanced');
})();
